version: '3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    ports:
      - "4200:4200"
    command: npm run start
    deploy:
      resources:
        limits:
          memory: 2g

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - /app/node_modules
    working_dir: /app
    ports:
      - "8080:8080"
    command: npm run dev

  jenkins:
    image: jenkins/jenkins:lts
    user: root
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    # Instala Docker CLI automáticamente
    entrypoint: ["/bin/sh", "-c", "apt-get update && apt-get install -y docker.io && /usr/bin/tini -- /usr/local/bin/jenkins.sh"]

volumes:
  jenkins_home:
